import { TRANSITIONS } from "../lib/deals/machine";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export function generateSeedSql(): string {
  const values = TRANSITIONS.map(
    (t) =>
      `('${t.from}', '${t.action}', '${t.to}', '${t.actor}', ${
        t.mode === null ? "null" : `'${t.mode}'`
      })`
  ).join(",\n  ");
  return [
    "-- GENERATED by scripts/generate-transitions-sql.ts — do not hand-edit.",
    "truncate table public.deal_transitions;",
    "insert into public.deal_transitions (from_status, action, to_status, actor_role, mode) values",
    `  ${values};`,
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  // NOTE: once 0005 has been applied to a hosted project, editing it in place
  // will NOT redeploy (the CLI records applied migrations by name). For any
  // transition change after hosted deploy, emit a NEW timestamped migration
  // instead of regenerating this file.
  writeFileSync("supabase/migrations/0005_transitions_seed.sql", generateSeedSql());
  console.log(`wrote ${TRANSITIONS.length} transitions`);
}
