-- Barter flow: reseed transitions, restore published→approve path, product-received timer, two-sided reviews.

alter table public.deals
  add column if not exists product_received_at timestamptz,
  add column if not exists preview_due_at timestamptz;

alter table public.brand_profiles
  add column if not exists slug citext unique
  check (slug is null or slug ~ '^[a-z0-9-]{3,40}$');

-- Backfill brand slugs from company name (best-effort).
update public.brand_profiles bp
set slug = sub.slug
from (
  select
    user_id,
    lower(regexp_replace(regexp_replace(trim(company), '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')) as slug
  from public.brand_profiles
  where company is not null and trim(company) <> ''
) sub
where bp.user_id = sub.user_id
  and bp.slug is null
  and length(sub.slug) >= 3;

-- GENERATED by scripts/generate-transitions-sql.ts — do not hand-edit.
truncate table public.deal_transitions;
insert into public.deal_transitions (from_status, action, to_status, actor_role, mode) values
  ('requested', 'accept', 'accepted', 'creator', null),
  ('requested', 'decline', 'cancelled', 'creator', null),
  ('requested', 'expire_accept', 'cancelled', 'system', null),
  ('accepted', 'mark_product_sent', 'product_sent', 'brand', 'barter'),
  ('product_sent', 'mark_product_received', 'product_received', 'creator', 'barter'),
  ('product_received', 'submit_preview', 'submitted', 'creator', 'barter'),
  ('accepted', 'submit_preview', 'submitted', 'creator', 'escrow'),
  ('accepted', 'submit_preview', 'submitted', 'creator', 'off_platform'),
  ('revision_requested', 'submit_preview', 'submitted', 'creator', null),
  ('submitted', 'request_revision', 'revision_requested', 'brand', null),
  ('submitted', 'approve_preview', 'submitted', 'brand', null),
  ('submitted', 'mark_published', 'published', 'creator', null),
  ('published', 'approve', 'completed', 'brand', null),
  ('published', 'auto_approve', 'completed', 'system', null),
  ('requested', 'cancel', 'cancelled', 'brand', null),
  ('accepted', 'cancel', 'cancelled', 'brand', null),
  ('accepted', 'cancel', 'cancelled', 'creator', null),
  ('accepted', 'dispute', 'disputed', 'brand', null),
  ('accepted', 'dispute', 'disputed', 'creator', null),
  ('product_sent', 'dispute', 'disputed', 'brand', null),
  ('product_sent', 'dispute', 'disputed', 'creator', null),
  ('product_received', 'dispute', 'disputed', 'brand', null),
  ('product_received', 'dispute', 'disputed', 'creator', null),
  ('submitted', 'dispute', 'disputed', 'brand', null),
  ('submitted', 'dispute', 'disputed', 'creator', null),
  ('revision_requested', 'dispute', 'disputed', 'brand', null),
  ('revision_requested', 'dispute', 'disputed', 'creator', null),
  ('published', 'dispute', 'disputed', 'brand', null),
  ('published', 'dispute', 'disputed', 'creator', null),
  ('disputed', 'resolve_release', 'completed', 'admin', null),
  ('disputed', 'resolve_refund', 'cancelled', 'admin', null);

drop function if exists public.transition_deal(uuid, text, text, jsonb);

create function public.transition_deal(
  p_deal_id uuid,
  p_action text,
  p_actor_role text,
  p_payload jsonb default '{}'
) returns public.deals
language plpgsql security definer set search_path = ''
as $$
declare
  v_deal public.deals;
  v_transition public.deal_transitions;
  v_uid uuid := auth.uid();
  v_preview text := nullif(p_payload->>'preview_url', '');
  v_live text := nullif(p_payload->>'live_url', '');
  v_note text := nullif(p_payload->>'revision_note', '');
  v_preview_days int := 3;
  v_sys_msg text;
begin
  select * into v_deal from public.deals where id = p_deal_id for update;
  if not found then raise exception 'deal not found'; end if;

  if p_actor_role = 'brand' and v_deal.brand_id is distinct from v_uid then
    raise exception 'not the brand on this deal';
  elsif p_actor_role = 'creator' and v_deal.creator_id is distinct from v_uid then
    raise exception 'not the creator on this deal';
  elsif p_actor_role = 'admin' and not exists (
    select 1 from public.profiles where id = v_uid and role = 'admin') then
    raise exception 'not an admin';
  elsif p_actor_role = 'system' and v_uid is not null then
    raise exception 'system transitions only from service role';
  end if;

  select * into v_transition from public.deal_transitions t
  where t.from_status = v_deal.status
    and t.action = p_action
    and t.actor_role = p_actor_role
    and (t.mode is null or t.mode = v_deal.payment_mode);
  if not found then
    raise exception 'illegal transition: % via % as % (mode %)',
      v_deal.status, p_action, p_actor_role, v_deal.payment_mode;
  end if;

  if p_action = 'request_revision' and v_deal.revision_count >= v_deal.revision_limit then
    raise exception 'revision limit reached';
  end if;

  if p_action = 'submit_preview' then
    if v_preview is null or v_preview !~* '^https?://' then
      raise exception 'submit_preview requires an http(s) preview_url';
    end if;
  end if;
  if p_action = 'mark_published' then
    if v_live is null or v_live !~* '^https?://' then
      raise exception 'mark_published requires an http(s) live_url';
    end if;
  end if;

  if p_action = 'mark_product_received' and v_deal.offering_id is not null then
    select coalesce(o.turnaround_days, 3) into v_preview_days
    from public.offerings o
    where o.id = v_deal.offering_id;
  end if;

  update public.deals set
    status = v_transition.to_status,
    revision_count = revision_count
      + (case when p_action = 'request_revision' then 1 else 0 end),
    preview_url = case when p_action = 'submit_preview' then v_preview else preview_url end,
    live_url = case when p_action = 'mark_published' then v_live else live_url end,
    last_revision_note = case when p_action = 'request_revision' then v_note else last_revision_note end,
    accepted_at  = case when v_transition.to_status = 'accepted'  then now() else accepted_at end,
    submitted_at = case when v_transition.to_status = 'submitted' then now() else submitted_at end,
    published_at = case when p_action = 'mark_published' then now() else published_at end,
    product_received_at = case when p_action = 'mark_product_received' then now() else product_received_at end,
    preview_due_at = case
      when p_action = 'mark_product_received' then now() + make_interval(days => v_preview_days)
      else preview_due_at
    end,
    completed_at = case when v_transition.to_status = 'completed' then now() else completed_at end,
    cancelled_at = case when v_transition.to_status = 'cancelled' then now() else cancelled_at end
  where id = p_deal_id
  returning * into v_deal;

  insert into public.deal_events (deal_id, actor, action, from_status, to_status, metadata)
  values (p_deal_id, v_uid, p_action, v_transition.from_status, v_transition.to_status,
          coalesce(p_payload, '{}'::jsonb));

  if v_deal.conversation_id is not null then
    v_sys_msg := case p_action
      when 'accept' then 'Creator accepted the deal'
      when 'decline' then 'Creator declined the deal'
      when 'mark_product_sent' then 'Brand marked the product as sent'
      when 'mark_product_received' then 'Creator marked the product as received'
      when 'submit_preview' then 'Preview submitted: ' || coalesce(v_preview, '')
      when 'approve_preview' then 'Brand approved the preview — clear to publish'
      when 'request_revision' then 'Brand requested changes: ' || coalesce(v_note, '(no note)')
      when 'mark_published' then 'Content published: ' || coalesce(v_live, '') || ' — awaiting brand approval'
      when 'approve' then 'Brand approved — deal complete'
      when 'auto_approve' then 'Auto-approved after 5 days'
      when 'cancel' then p_actor_role || ' cancelled the deal'
      when 'dispute' then p_actor_role || ' opened a dispute'
      when 'expire_accept' then 'Deal expired (no response in 72h)'
      when 'resolve_release' then 'Dispute resolved — deal completed'
      when 'resolve_refund' then 'Dispute resolved — deal refunded'
      else p_action
    end;

    insert into public.messages (conversation_id, sender_id, body, kind, deal_id_ref)
    values (v_deal.conversation_id, null, v_sys_msg, 'system', v_deal.id);
  end if;

  return v_deal;
end;
$$;

revoke all on function public.transition_deal(uuid, text, text, jsonb) from public;
grant execute on function public.transition_deal(uuid, text, text, jsonb)
  to authenticated, service_role;

create or replace function public.run_deal_timers() returns integer
language plpgsql security definer set search_path = ''
as $$
declare
  r record;
  n integer := 0;
begin
  for r in
    select id from public.deals
    where status = 'requested'
      and requested_at < now() - interval '72 hours'
  loop
    begin
      perform public.transition_deal(r.id, 'expire_accept', 'system');
      n := n + 1;
    exception when others then
      null;
    end;
  end loop;

  for r in
    select id from public.deals
    where status = 'published'
      and published_at < now() - interval '5 days'
  loop
    begin
      perform public.transition_deal(r.id, 'auto_approve', 'system');
      n := n + 1;
    exception when others then
      null;
    end;
  end loop;

  -- Barter preview deadline: expose via preview_due_at; no auto-cancel policy yet.
  -- Deals where status = 'product_received' and preview_due_at < now() remain
  -- actionable until a future expire_preview policy is added.

  return n;
end;
$$;

-- Creator → brand reviews (public projection).
create or replace view public.public_brand_reviews
  with (security_invoker = off) as
select r.id, r.deal_id, d.brand_id, r.rating, r.body, r.created_at
from public.reviews r
join public.deals d on d.id = r.deal_id
where r.author_id = d.creator_id;

grant select on public.public_brand_reviews to anon, authenticated;
